apiVersion: apps/v1
kind: Deployment
metadata:                  # 3가지 필수 구성요소중 하나
  name: myweb-deployment           # 해당 이름으로 디플로이 먼트가 생성됨.
  labels:
    app: myweb
spec:                      # 3가지 필수 구성요서중 하나 specification, 나머지 하나는 status
  replicas: 4              # 2개의 리플리카 pod를 생성한다.
  selector:                # 디플로이먼트가 관리할 파드를 찾는 방법을 정의, matchLabels이 myweb인 파드를 디플로이먼트가 관리한다.
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb              # 파드는 .metadata.labels 필드를 사용 app: myweb 라는 레이블을 붙인다.
    spec:
      containers:
      - name: myweb            # 컨테이너 1개를 생성, .spec.template.spec.containers[0].name 필드를 사용해서 myweb 라는 이름을 붙인다.
        image: public.ecr.aws/q3b4u2r0/myweb:1.0 # 파드가 도커 허브의 myweb 1.0 버전 이미지를 실행하는 myweb 컨테이너 1개를 실행하는 것을 나타낸다.
        ports:
        - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: NodePort
  selector:
    app: myweb
  clusterIP: 172.17.10.100
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
